### ISSUE TITLE
k_min implementation

### ISSUE THREAD

**Issue by arnava13** [arnava13/SeniorHonoursProject#1]
Following my new implementation of k_min, when running the training with k_min $\neq$ 0 results in training completing under 10 seconds with the following error in the output flow:

```
err: Traceback (most recent call last):
err: File "/content/SeniorHonoursProject/BaCoN-II/train.py", line 641, in <module>
err: main()
err: File "/content/SeniorHonoursProject/BaCoN-II/train.py", line 488, in main
err: model=make_model(     model_name=model_name,
err: File "/content/SeniorHonoursProject/BaCoN-II/models.py", line 21, in make_model
err: return make_custom_model(**params)
err: File "/content/SeniorHonoursProject/BaCoN-II/models.py", line 106, in make_custom_model
err: x=conv1(x)
err: File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
err: raise e.with_traceback(filtered_tb) from None
err: File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/layers/conv_variational.py", line 226, in call
err: outputs = self._apply_variational_kernel(inputs)
err: File "/usr/local/lib/python3.10/dist-packages/tensorflow_probability/python/layers/conv_variational.py", line 1071, in _apply_variational_kernel
err: outputs = self._convolution_op(
err: ValueError: Exception encountered when calling layer "conv1d_flipout_2" (type Conv1DFlipout).
err: Negative dimension size caused by subtracting 2 from 1 for '{{node conv1d_flipout_2/conv1d}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](conv1d_flipout_2/conv1d/ExpandDims, conv1d_flipout_2/conv1d/ExpandDims_1)' with input shapes: [?,1,1,16], [1,2,16,32].
err: Call arguments received by layer "conv1d_flipout_2" (type Conv1DFlipout):
err: • inputs=tf.Tensor(shape=(None, 1, 16), dtype=float32)
out: Creating directory models/sixlabel_1001_EE2_equalexamples-randoms_kmin-0.5_kmax-5.0_
out: Logger creating log file: models/sixlabel_1001_EE2_equalexamples-randoms_kmin-0.5_kmax-5.0_/sixlabel_1001_EE2_equalexamples-randoms_kmin-0.5_kmax-5.0__log.txt
```

**Comment by arnava13** [comment]
Error disappears when training with 200 k modes at a sample rate of 4.

**Comment by arnava13** [comment]
Using padding = same is a potential solution
